apiVersion: v1
kind: Service

metadata:
  name: aws-enterprise-devops-service

spec:
  selector:
    app: aws-enterprise-devops

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort
